#!/bin/bash

echo "🔧 GUÍA PARA CONFIGURAR MONGODB ATLAS"
echo "===================================="
echo ""
echo "📋 PASOS A SEGUIR EN MONGODB ATLAS:"
echo ""
echo "1️⃣ Ve a: https://cloud.mongodb.com"
echo "2️⃣ Inicia sesión con tu cuenta"
echo "3️⃣ Selecciona tu proyecto/cluster"
echo "4️⃣ Ve a 'Network Access' (en el menú lateral)"
echo "5️⃣ Haz clic en 'ADD IP ADDRESS'"
echo "6️⃣ Selecciona 'ALLOW ACCESS FROM ANYWHERE'"
echo "7️⃣ O agregar manualmente: 0.0.0.0/0"
echo "8️⃣ Haz clic en 'Confirm'"
echo ""
echo "📝 CREDENCIALES ACTUALES:"
echo "Usuario: adelgadoq"
echo "Password: EOt9BLdXCNmZWekA"
echo "Cluster: cluster0.odu4rtq.mongodb.net"
echo "Database: delizia"
echo ""
echo "🔗 STRING DE CONEXIÓN:"
echo "mongodb+srv://adelgadoq:EOt9BLdXCNmZWekA@cluster0.odu4rtq.mongodb.net/delizia?retryWrites=true&w=majority"
echo ""
echo "⚠️  IMPORTANTE: Sin este paso, Vercel no puede conectar a MongoDB"
echo ""

# Probar la conexión después de la configuración
echo "🧪 PROBANDO CONEXIÓN ACTUAL..."
curl -s -X GET "https://api-delizia.vercel.app/api/diagnostico" | grep -E "(success|error|mongoConnected)"

echo ""
echo "✅ Después de configurar Network Access, ejecuta:"
echo "   curl -X GET 'https://api-delizia.vercel.app/api/diagnostico'"
